name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Test Coverage
        run: mvn -B --file pom.xml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco/

